print("what do you call a magic dog?")
input()
print("a labracadabrador")
input()
print("why was the frog late to work?")
input()
print("his car got toad")
input()
print("when does a joke become a 'dad joke'")
input()
print("when it becomes apparent")